#!/bin/bash
wget https://github.com/wellzin-blip/new2022/raw/master/Painel-V2022/checkuser.py > /dev/null 2>&1
chmod 777 checkuser.py > /dev/null 2>&1 
python checkuser.py 5050 > /dev/null 2>&1
figlet "CHECK4G" | lolcat
echo ""
echo '░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░' | lolcat
IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
echo -e "$green CHECKUSER INSTALADO"
echo ""
echo -e "http://$IP:5050/checkUser"
echo ""
echo '░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░' | lolcat
echo -e "$yellow Pressione enter para voltar." ; read enter ; checkers